### ISSUE TITLE
localgb.py is missing import gzip

### ISSUE THREAD

**Issue by evolgenomology** [mojones/localgb#1]
Hi Martin,

absolutely brilliant stuff. Thanks a lot.
Just got an error when wanting to `query.py`
`looking for "product"
  0%|                                                                                                                                                                      | 0/362 [00:00<?, ?files/s]
Traceback (most recent call last):
  File "query.py", line 118, in <module>
    localgb.do_search(args)
  File "/GenomeData_telfordNAS/localgb/localgb.py", line 351, in do_search
    genbank_file = gzip.open(filename, mode="rt", encoding='latin-1')
NameError: name 'gzip' is not defined`

Fix was to add `import gzip` to `localgb.py`.

Cheers

Philipp

**Comment by mojones** [comment]
Fixed! Sorry for the slow reply; I had kind of forgotten I put this up :-)
